version: 2

sources:
  - name: raw
    description: "Raw e-commerce data"
    database: production
    schema: public
    tables:
      - name: raw_customers
        description: "Customer master data"
        columns:
          - name: id
            description: "Unique customer identifier"
          - name: email
            description: "Customer email address"
          - name: name
            description: "Customer full name"
          - name: created_at
            description: "Account creation timestamp"

      - name: raw_orders
        description: "Order transactions"
        columns:
          - name: order_id
            description: "Unique order identifier"
          - name: customer_id
            description: "Reference to customer"
          - name: order_date
            description: "Order placement date"
          - name: total_amount
            description: "Order total in USD"
          - name: status
            description: "Order status (pending, completed, shipped)"
